#!/usr/bin/env bash
# script displays information about domains.
domain_name="$1"
loop2 (){
for arg
do
    echo -n "The subdomain '$arg' is a "
    dig "$arg.$domain_name" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $4 " record and points to " $5}'
done
}
if [ $# -lt 2 ]
then
    loop2 www lb-01 web-01 web-02
else
    loop2 "$2"
fi
