#!/usr/bin/env bash
#script that adds a HTTP header to a server
sudo apt-get update
sudo apt-get -y install nginx
sed -i '24i\               add_header X-Served-By: 534-web-02' /etc/nginx/sites-available/default;
service nginx restart
