#!/usr/bin/env bash
# Configure ubuntu machine to install and Configure HAproxy
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.6
sudo apt-get update -y
sudo apt-get install haproxy=1.6.\* -y
configuration="frontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\nbackend backendnodes\n\tbalance roundrobin\n\toption forwardfor\n\tserver web-01 35.237.164.107\n\tserver web-02 35.243.176.56\n"
echo -e "$configuration" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
