#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump -u root -p --all-databases > backup.sql
now=$(date +"%d-%m-%Y")
tar cfz "$now".tar.gz backup.sql
