#!/usr/bin/env bash
#Bash that prints Holberton School and on 9 prints Hi.
x=1
while [ $x -le 10 ]
do
    echo "Holberton School"
    if [ $x -eq 9 ]
    then
        echo "Hi"
    fi
    x=$((x + 1))
done
