#!/usr/bin/env bash
#Bash script that displays a clock
x=0
while [ $x -le 12 ]
do
    echo "Hour: "$x
    y=1
    while [ $y -le 59 ]
    do
        echo $y
        y=$((y + 1))
    done
((x ++))
done
